name = "ReversibleTuringMachine"
uuid = "c12bd296-1586-4d52-ba8d-0df17f75a654"
authors = ["GiggleLiu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
